# AI Batch 35 (PIAIC91502) Quarter 2 # 

# implentation of any 50 numpy methods or attribute codes in jupyter notebook


In [2]:
import numpy as np

In [2]:
# 1. One dimensional Array function 

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
# 2. Array type function 

In [8]:
type(arr)

numpy.ndarray

In [ ]:
# 3. Change data type

In [17]:
arr = np.array([1.1, 2.1, 3.1])
iarr = arr.astype("i")
print(iarr)
print(iarr.dtype)


[1 2 3]
int32


In [18]:
# 4. Copy function ....Make a copy, change the original array, and display both arrays:

In [19]:
arr = np.array(["safdar", "gohar", "khawar"])
copy_arr = arr.copy()
arr[0] = "khan"
print(copy_arr)
print(arr)

['safdar' 'gohar' 'khawar']
['khan' 'gohar' 'khawar']


In [ ]:
# 5. Reshape function ..........Reshape From 1-D to 4-D

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
# 6. nditer() ........Iterating on Each Scalar Element

In [26]:
arr = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# 7. ndenumerate() .........Enumerate on following 1D arrays elements

In [31]:
arr = np.array([1,2,3,4,5])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [32]:
# 8. Concatenate()  ............. join two arrays

In [37]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_new = np.concatenate((arr1, arr2))
arr_new


array([1, 2, 3, 4, 5, 6])

In [ ]:
# 9. stack() ......... joining arrays 

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_new = np.stack((arr1, arr2))
arr_new

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 10. hstack() .......... Stacking along rows

In [5]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_new = np.hstack((arr1, arr2))
arr_new

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 11. vstack() .......... Stacking along columns

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_new = np.vstack((arr1, arr2))
arr_new

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
# 12. dstack() .......... Stacking along height

In [7]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr_new = np.dstack((arr1, arr2))
arr_new

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [ ]:
# 13. array_split()     ..... Split the array in 3 parts:

In [11]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
# 14. hsplit() ............  Use the hsplit() method to split the 2-D array into three 2-D arrays along rows

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [13]:
# 15. where() ..........Search an array and get index

In [14]:
arr = np.array([3, 4, 5])
newarray = np.where(arr == 5)
newarray

(array([2], dtype=int32),)

In [ ]:
# 16. searchsorted() .......... Find the indexes where the value 7 should be inserted: 

In [16]:
arr = np.array([3, 4, 5, 6, 7, 8])
newarray = np.searchsorted(arr, 7)
newarray

4

In [17]:
# 17. sort() ............ sort the array

In [19]:
arr = np.array([4, 2, 0, 6])
new_arr = np.sort(arr)
new_arr

array([0, 2, 4, 6])

In [20]:
# 18. zeros() .......... Create zero array 3 dinmensional

In [25]:
arr = np.zeros((3, 3), float)
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# 19. ones() .......... Create ones array 3 dinmensional

In [26]:
arr = np.ones((3, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 20. empty() ......... Create empty array 

In [27]:
arr = np.empty((4, 4))
arr

array([[ 7.56579435e-307,  1.78019625e-306,  1.06810268e-306,
         1.24612081e-306],
       [-3.26911508e-310,  1.01857352e-312,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [-3.31388922e-310,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]])

In [ ]:
# 21. arange() ...........create arrays with regularly incrementing values

In [31]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [32]:
# 22. linspace() ..........   create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [35]:
arr = np.linspace(1,20)
arr

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [ ]:
# 23. cumsum() ......return cumulative sum 

In [38]:
arr = np.arange(1, 10)
n = np.cumsum(arr)
n

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [ ]:
# 24. flatten() ......get a copy of an given array collapsed into one dimension

In [41]:
arr = np.array([[1,2],[3,4]])
arr.flatten()

array([1, 2, 3, 4])

In [ ]:
# 25. ravel() ......... create a contiguous flattened array

In [43]:
arr = np.array([[1,2],[3,4]])
np.ravel(arr)

array([1, 2, 3, 4])

In [ ]:
# 26. tile() ........tile() function is used to construct an array by repeating A the number of times given by reps

In [44]:
arr = np.array([1,2,3])
np.tile(arr,2)

array([1, 2, 3, 1, 2, 3])

In [45]:
# 27. repeat() .......repeat() function is used to repeat elements of an array

In [49]:
arr = np.array([1,2,3])
np.repeat(arr, 33)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
# 28. flip() .... Reverse the order of elements in an array along the given axis

In [50]:
arr = np.array([1,2,3])
np.flip(arr)

array([3, 2, 1])

In [ ]:
# 29. unique() .... unique elements

In [53]:
arr = np.array([[1,2,3],[2,3,5]])
np.unique(arr)

array([1, 2, 3, 5])

In [54]:
# 30. roll() ....... Roll array elements along a given axis

In [55]:
arr = np.arange(10)
np.roll(arr, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [56]:
# 31. datetime64() .... Today date

In [57]:
today = np.datetime64("today", "D")
print(today)

2020-12-20


In [ ]:
# 32. Cross() .....Cross product of arrays

In [58]:
p = [[1, 2], [3, 4]]
q = [[5, 6], [7, 8]]

np.cross(p, q)

array([-4, -4])

In [ ]:
# 33. amax() ....  maximum number of array

In [61]:
p = [[1, 2, 3, 44]]
np.amax(p)

44

In [ ]:
# 34. amin() ....  minimum number of array

In [62]:
p = [[1, 2, 3, 44]]
np.amin(p)

1

In [ ]:
# 35. allclose() .....  Returns True if two arrays are element-wise equal within a tolerance

In [67]:
p = [1, 2]
q = [1, 2]

np.allclose(p,q)

True

In [ ]:
# 36. char.capitalize() .... Capitalize

In [71]:
x = np.array(["safdar"], dtype = np.str)
arr = np.char.capitalize(x)
arr

array(['Safdar'], dtype='<U6')

In [ ]:
# 37. char.lower()

In [72]:
x = np.array(["SAFDAR"], dtype = np.str)
arr = np.char.lower(x)
arr

array(['safdar'], dtype='<U6')

In [ ]:
# 38. swapcase()

In [73]:
x = np.array(["SAFDAR", "java", "php", "Gul Khan"], dtype = np.str)
arr = np.char.swapcase(x)
arr

array(['safdar', 'JAVA', 'PHP', 'gUL kHAN'], dtype='<U8')

In [74]:
# 39. title()

In [78]:
x = np.array(["SAFDAR", "java", "php", "Gul Khan"], dtype = np.str)
arr = np.char.title(x)
arr

array(['Safdar', 'Java', 'Php', 'Gul Khan'], dtype='<U8')

In [ ]:
# 40. encode()  ... encode the value

In [80]:
x = np.array(["SAFDAR", "java", "php", "Gul Khan"], dtype = np.str)
arr = np.char.encode(x, "cp500")
arr

array([b'\xe2\xc1\xc6\xc4\xc1\xd9', b'\x91\x81\xa5\x81', b'\x97\x88\x97',
       b'\xc7\xa4\x93@\xd2\x88\x81\x95'], dtype='|S8')

In [81]:
# 41. delete() ....  Return a new array with sub-arrays along an axis deleted. For a onedimensional array, this returns those entries not returned by`arr[obj]`.

In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.delete(arr, 1, 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
# 42. insert() ..... Insert values along the given axis before the given indices

In [90]:
x = np.array([[0,0], [1,1], [2,2]])

np.insert(x, 2, 4)


array([0, 0, 4, 1, 1, 2, 2])

In [ ]:
# 43. sum() ... add all items

In [91]:
x = np.array([[0,0], [1,1], [2,2]])
np.sum(x)

6

In [ ]:
# 44. min() ....  Return the minimum of an array or minimum along an axis.

In [92]:
x = np.array([[0,0], [1,1], [2,2]])
np.min(x)

0

In [ ]:
# 45. transpose() .....Reverse or permute the axes of an array; returns the modified array

In [93]:
x = np.arange(4).reshape((2,2))
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [ ]:
# 46. mean() ... mean of an array

In [94]:
a = np.array([1,2,3])
print("Mean value is :", a.mean())

Mean value is : 2.0


In [ ]:
# 47. setdiff1d() ... Find the set difference of two arrays.Return the unique values in `ar1` that are not in `ar2`

In [95]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [ ]:
# 48. intersect1d() ... Return the sorted, unique values that are in both of the input arrays

In [96]:
a = np.array([1,2,3,4,5,8])
b = np.array([5,6,7,8,9,1])
np.intersect1d(a,b)

array([1, 5, 8])

In [ ]:
# 49. tile() ....  Construct an array by repeating A the number of times given by reps

In [97]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [98]:
# 50 mod() ...  Return element-wise remainder of division.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

# Assignment no 1 Numpy.   AI Batch 35 (PIAIC91502) solution 

In [ ]:
Import the numpy package under the name np

In [2]:
import numpy as np

In [ ]:
Create a null vector of size 10

In [4]:
null_vector = np.zeros(10)

In [5]:
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
Create a vector with values ranging from 10 to 49

In [8]:
value = np.array(range(10,50))

In [9]:
value 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
Find the shape of previous array in question 3

In [10]:
values.shape

(40,)

In [ ]:
Print the type of the previous array in question no 3

In [11]:
print(type(values))

<class 'numpy.ndarray'>


In [ ]:
Print the numpy version and the configuration 

In [12]:
print(np.__version__)

1.19.4


In [ ]:
Print the dimension of the array in question no 3

In [13]:
print(values.ndim)

1


In [ ]:
Create a boolean array with all the True values

In [20]:
bool_arr = np.ones(5, dtype = bool)

In [16]:
bool_arr

array([ True,  True,  True,  True,  True])

In [ ]:
Create a two dimensional array

In [19]:
arr_2D = np.array([[1, 2], [11, 22]])
arr_2D

array([[ 1,  2],
       [11, 22]])

In [ ]:
Create a three dimensional array

In [21]:
import random

In [22]:
arr_3D = np.random.randn(3, 2, 2)

In [23]:
arr_3D

array([[[ 2.49295556, -0.17199095],
        [-0.53028586,  0.94406961]],

       [[ 1.50581803,  0.68543234],
        [ 3.00119189,  0.77404488]],

       [[ 0.71631464,  1.26158607],
        [ 0.85931895,  0.33313974]]])

In [ ]:
Reverse a vector (first element becomes last)

In [29]:
val = np.arange(1, 10)
val_rev = val[::-1]
val_rev

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
Create a null vector of size 10 but the fifth value which i s1

In [30]:
null_vect = np.zeros(10)
null_vect[4] = 1
null_vect

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
Create a 3 x 3 identity matrix

In [32]:
id_mat = np.identity(3)
id_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3,4,5])
Convert the data type of the given array from int to float

In [34]:
arr = np.array([1,2,3,4,5])
arr_flot = np.array(arr, dtype = 'float')
arr_flot

array([1., 2., 3., 4., 5.])

In [ ]:
Convert the data type of the given array from int to float

arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [37]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr1_float = np.array(arr1, dtype = 'float')
arr1_float

array([[1., 2., 3.],
       [4., 5., 6.]])

In [38]:
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr2_float = np.array(arr2, dtype = 'float')
arr2_float

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [ ]:
Multiply arr1 with arr2

In [3]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [ ]:
Make an array by comparing both the arrays provided above

In [4]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1 == arr2

array([[False, False, False],
       [False, False, False]])

In [ ]:
Extract all odd numbers from arr with values(0-9)

In [5]:
arr1 =np.array(range(10)) 
for i in arr1:
    if i%2==1:
        print(i)

1
3
5
7
9


In [ ]:
Replace all odd numbers to -1 from previous array

In [8]:
arr1 =np.array(range(10)) 
for i in arr1:
    if i%2==1:
        print(i)
        arr1[i] =-1
print(arr1)
arr = np.arange(10)
arr

1
3
5
7
9
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [9]:

arr = np.arange(10)
for i in arr:
    if i==5 or i==6 or i==7 or i==8:
        arr[i] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


In [ ]:
Create a 2d array with 1 on the border and 0 inside

In [10]:
arr = np.ones((4,4))
arr[1:3,1:3]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
Replace the value 5 to 12

In [11]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1] =  12  
print(arr2d)
arr2d.ndim

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


2

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
Convert all the values of 1st array to 64

In [12]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:][0,:] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [13]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr1d = arr2d[0,:]
arr1d

array([1, 2, 3])

In [ ]:
Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [14]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr1d = arr2d[1,1]
arr1d

5

In [ ]:
Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [15]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr1d = arr2d[0:2,-1]
arr1d

array([3, 6])

In [ ]:
Create a 10x10 array with random values and find the minimum and maximum values

In [16]:

arr10 =np.random.randn(10,10)
np.min(arr10), np.max(arr10)

(-2.455919383988332, 2.728528321002396)

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
Find the common items between a and b


In [17]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [ ]:
Find the positions where elements of a and b match

In [18]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.searchsorted(a, np.intersect1d(a, b))

array([1, 5], dtype=int32)

In [ ]:
Find all the values from array data where the values from array names are not equal to Will

In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(data)
print('end')
print(data[names !='Will'])

[[ 1.77393283 -1.26605017 -0.07219686 -0.86420604]
 [ 0.18737967 -0.04383307 -0.31720447  0.13317897]
 [ 0.3215258   1.0325029   0.95703864 -1.41702059]
 [ 1.13237286 -0.7622363  -1.50139162  0.51909496]
 [ 0.66495629 -0.93416758  0.51551178  0.88439724]
 [ 0.24295032  1.8975392   0.77489994 -2.80383958]
 [-0.58445171  0.47343706  0.11167994 -2.54795363]]
end
[[ 1.77393283 -1.26605017 -0.07219686 -0.86420604]
 [ 0.18737967 -0.04383307 -0.31720447  0.13317897]
 [ 1.13237286 -0.7622363  -1.50139162  0.51909496]
 [ 0.24295032  1.8975392   0.77489994 -2.80383958]
 [-0.58445171  0.47343706  0.11167994 -2.54795363]]


In [ ]:
Find all the values from array data where the values from array names are not equal to Will and Joe

In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

print(data[(names != 'Will') & (names != "ali")])

[[-0.73899736  1.17224917  0.28465585  0.74688808]
 [ 0.92833404  1.47715456 -0.04208704  0.48243255]
 [ 0.03189094 -0.22515384  1.22057724 -0.4540654 ]
 [-0.40586393  0.37161213  1.85439922  0.67319049]
 [-0.18417289  1.30731693 -1.45393396 -2.00867709]]


In [ ]:

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [21]:
arr2D = np.arange(1,16,dtype='float').reshape(5,3)
arr2D

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

In [ ]:
Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [23]:

arr3D = np.arange(1,17,dtype='float').reshape(2,2,4)
arr3D

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [ ]:
Swap axes of the array you created in Question 32

In [24]:
arr3D = np.arange(1,17,dtype='float').reshape(2,2,4)

np.swapaxes(arr3D,1,2)

array([[[ 1.,  5.],
        [ 2.,  6.],
        [ 3.,  7.],
        [ 4.,  8.]],

       [[ 9., 13.],
        [10., 14.],
        [11., 15.],
        [12., 16.]]])

In [ ]:
Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [25]:

arr1 = np.random.randn(10)
square_arr1 = arr1 * arr1
print(square_arr1)
x=0
for i in square_arr1:
    if i<0.5:
        square_arr1[x]=0
    x=x+1
square_arr1

[0.20334551 0.02171666 0.11038311 0.94143454 1.36831646 1.14919699
 0.03459357 0.10111201 0.2399515  3.39061698]


array([0.        , 0.        , 0.        , 0.94143454, 1.36831646,
       1.14919699, 0.        , 0.        , 0.        , 3.39061698])

In [ ]:
Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays


In [26]:

arr1 = np.random.randn(10)
arr2 = np.random.randn(10)
np.maximum(arr1,arr2)


array([ 0.1373535 ,  0.58679616, -0.31964434,  0.42039404,  0.06570125,
        0.80922776,  1.35182097,  1.18012506,  1.6661695 ,  1.32246394])

In [ ]:
Find the unique names and sort them out!



In [27]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])

From array a remove all items present in array b

In [28]:

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a= np.setdiff1d(a,b)
a

array([1, 2, 3, 4])

In [ ]:
array([1, 2, 3, 4])
Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [29]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[0,:] = newColumn
sampleArray

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[10, 10, 10],
       [82, 22, 12],
       [53, 94, 66]])

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])

Find the dot product of the above two matrix

In [30]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [ ]:
Generate a matrix of 20 random values and find its cumulative sum

In [31]:

rand = np.random.randn(20)
print(rand)
sum(rand)

[-0.13172519  1.03414668  0.02885031 -0.2613508   1.40186846 -2.25767272
  0.51013815  2.6102436  -1.60756572  0.0925174  -1.18115718  0.06342819
  0.79866689 -0.90831284  0.91509253 -1.12281369 -0.17197096  0.03366733
  0.65600808  0.42714094]


0.9291994525280456